# Build and test the android application
name: Android

on:
  push:
    branches:
      - master

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: ./android
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew
      - name: Build App
        shell: bash
        run: |
          # To run the CI with debug informations, add --info
          ./gradlew assemble --parallel --build-cache
      - name: Run tests
        shell: bash
        run: |
          # To run the CI with debug informations, add --info
          ./gradlew check --parallel --build-cache
      - name: Generate Coverage Report
        shell: bash
        run: |
          # To run the CI with debug informations, use --info
          ./gradlew jacocoTestReport --parallel --build-cache
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ANDROID}
        run: |
          # To run the CI with debug informations, use --info
          ./gradlew sonarqube --parallel --build-cache
