# Test the ledger modules
name: Ledger (go)

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ledger
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis

      - name: Use go >= 1.18  
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'

      - name: Build OpenSSL
        run: |
          url="https://openssl.org/source/openssl-3.0.3.tar.gz"
          OS_COMPILER=linux-x86_64
          OPENSSL_DIR=/opt/openssl

          mkdir /tmp/build
          cd /tmp/build
          curl -L $url | tar --strip-components=1 -xzf -
          ./Configure --prefix=$OPENSSL_DIR --libdir=lib $OS_COMPILER -fPIC -g $OS_FLAGS no-shared
          make
          make install_sw

      - name: Test all
        run: |
          go test -v -coverpkg=./... -coverprofile=coverage.out ./... -json > report.json

      - name: Run code analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ledger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_LEDGER }}