name: Go lint

on:
  push:
    branches: [ main ]

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
    contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: ./server

    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis
      
    - name: Lint
      run: make lint

    - name: Vet
      run: make vet