name: Server test

on:
  push:
    branches: [ main ]

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}

    defaults:
      run:
        working-directory: ./server

    env:
      LLVL: trace

    steps:
      - name: Set up Go ^1.19
        uses: actions/setup-go@v3
        id: go
        with:
            go-version: '^1.19'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis

      - name: Test without coverage
        if: matrix.platform == 'macos-latest' || matrix.platform == 'windows-latest'
        run: make test

      - name: Test with coverage
        if: matrix.platform == 'ubuntu-latest'
        run: make coverage

      - name: Run code analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
            projectBaseDir: server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Send coverage
        if: matrix.platform == 'ubuntu-latest'
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          parallel: true
        
  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true