name: Go lint

on:
  push:
    branches: [ main ]

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
    contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v3
      id: go
      with:
        go-version: '^1.19'

    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis

    - name: Lint
      working-directory: ./server
      run: make lint

    - name: Vet
      working-directory: ./server
      run: make vet